language: go

go:
  - "1.14"
  - "1.15"

env:
  - ROS_DOCKER=ros:kinetic-ros-base
  - ROS_DOCKER=ros:melodic-ros-base
  - ROS_DOCKER=ros:noetic-ros-base

services:
  - docker

install:
  - docker build -f .travis/Dockerfile -t akio/rosgo . --build-arg ROS_DOCKER_TAG=$ROS_DOCKER

script:
  - docker run -v $(go env GOROOT):/usr/local/go akio/rosgo
